# 컬럼명 변경 및 데이터 불러오기

In [62]:
import pandas as pd
jeju = pd.read_csv("제주관광지_필터링.csv",encoding="utf-8")
jeju.tail()

       위치좌표 X축값   위치좌표 Y축값       구분        장소명                        소재지
6505  126.674899  33.544272  레져/스포츠  함덕해수욕장야영장    제주특별자치도 제주시 조천읍 함덕리 산 4
6506  126.735810  33.382333  레져/스포츠   조랑말공원캠프장  제주특별자치도 서귀포시 표선면 가시리 산 41
6507  126.366465  33.475708   관광/숙박    BE2IN팬션    제주특별자치도 제주시 애월읍 신엄9길 51
6508  126.366841  33.449328   관광/숙박     하늬바람펜션    제주특별자치도 제주시 애월읍 신상로 258
6509  126.512445  33.233646   관광/숙박      플라야팬션      제주특별자치도 서귀포시 법환동 1447

In [63]:
jeju.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6510 entries, 0 to 6509
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   위치좌표 X축값   6510 non-null   float64
 1   위치좌표 Y축값   6510 non-null   float64
 2   구분         6510 non-null   object
 3   장소명        6510 non-null   object
 4   소재지        6510 non-null   object
dtypes: float64(2), object(3)
memory usage: 254.4+ KB

In [64]:
jeju.columns

Index(['위치좌표 X축값 ', '위치좌표 Y축값 ', '구분', '장소명', '소재지'], dtype='object')

In [65]:
jeju.rename(columns = {'위치좌표 X축값 ' : 'x','위치좌표 Y축값 ' : "y"}, inplace = True)

In [66]:
jeju.head()

            x          y     구분     장소명                       소재지
0  126.495979  33.486592  관광/숙박  코리아나호텔     제주특별자치도 제주시 연동 303-10
1  126.385364  33.470809  관광/숙박   수산유원지  제주특별자치도 제주시 애월읍 수산리 1918
2  126.771241  33.529109  관광/숙박     만장굴    제주특별자치도 제주시 구좌읍 월정리 41
3  126.941753  33.458386  관광/숙박   성산일출봉  제주특별자치도 서귀포시 성산읍 신천리 114
4  126.394439  33.408524  관광/숙박  제주경마공원  제주특별자치도 제주시 애월읍 소길리 1206

# 전처리

## 1. 좌표 값이 같고 이름이 다른 경우(중복 장소 제거)

False

## 2. 관광/숙박 시설 나누기

In [87]:
jeju_split = pd.read_excel("POI_관광_숙박.xlsx")
jeju_split

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name
0,0,126.495979,33.486592,관광/숙박,코리아나호텔,제주특별자치도 제주시 연동 303-10,.
1,1,126.385364,33.470809,관광/숙박,수산유원지,제주특별자치도 제주시 애월읍 수산리 1918,.
2,2,126.771241,33.529109,관광/숙박,만장굴,제주특별자치도 제주시 구좌읍 월정리 41,"(거문오름용암동굴계)만장굴,(제주화산섬과용암동굴)만장굴"
3,3,126.941753,33.458386,관광/숙박,성산일출봉,제주특별자치도 서귀포시 성산읍 신천리 114,"일출봉,(제주화산섬과용암동굴)성산일출봉"
4,4,126.394439,33.408524,관광/숙박,제주경마공원,제주특별자치도 제주시 애월읍 소길리 1206,"경마공원,제주경마장"
...,...,...,...,...,...,...,...
3696,4946,126.539649,33.517965,관광/숙박,다이아나호텔,제주특별자치도 제주시 건입동 658-1,다이아나관광호텔
3697,4947,126.619611,33.251045,관광/숙박,바람코지게스트하우스,제주특별자치도 서귀포시 하효동 1052-3,.
3698,4950,126.572698,33.453664,관광/숙박,국제전기자동차엑스포,제주특별자치도 제주시 영평동 2170-1,.
3699,5937,126.487942,33.489017,관광/숙박,케이호텔,제주특별자치도 제주시 연동 251-79,.
3700,5938,126.519219,33.254743,관광/숙박,서귀포라마다앙코르호텔,제주특별자치도 서귀포시 서호동 1524-7,.

In [88]:
jeju_accom = jeju_split.query('장소명.str.contains("호텔|민박|모텔|여관|리조트|펜션|여인숙|별장|콘도|팬션|호스텔|무인텔|하우스") or 장소명.str.endswith("텔")', engine='python')
jeju_accom

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name
0,0,126.495979,33.486592,관광/숙박,코리아나호텔,제주특별자치도 제주시 연동 303-10,.
6,6,126.394730,33.273239,관광/숙박,서귀포호텔,제주특별자치도 서귀포시 상예동 161,.
9,12,126.257018,33.222826,관광/숙박,실버스타호텔,제주특별자치도 서귀포시 대정읍 상모리 3967-13,.
10,13,126.308401,33.229885,관광/숙박,하동민박,제주특별자치도 서귀포시 안덕면 사계리 2032-4,.
12,15,126.335598,33.241884,관광/숙박,둥지민박,제주특별자치도 서귀포시 안덕면 화순리 804-1,.
...,...,...,...,...,...,...,...
3695,4945,126.531406,33.241578,관광/숙박,돔베리조트,제주특별자치도 서귀포시 호근동 1592,.
3696,4946,126.539649,33.517965,관광/숙박,다이아나호텔,제주특별자치도 제주시 건입동 658-1,다이아나관광호텔
3697,4947,126.619611,33.251045,관광/숙박,바람코지게스트하우스,제주특별자치도 서귀포시 하효동 1052-3,.
3699,5937,126.487942,33.489017,관광/숙박,케이호텔,제주특별자치도 제주시 연동 251-79,.
3700,5938,126.519219,33.254743,관광/숙박,서귀포라마다앙코르호텔,제주특별자치도 서귀포시 서호동 1524-7,.

In [89]:
for i in jeju_accom.index:
    jeju_split.drop(index = i,inplace=True)

In [90]:
jeju_split.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1773 entries, 1 to 3698
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1773 non-null   int64
 1   위치좌표 X축값         1773 non-null   float64
 2   위치좌표 Y축값         1773 non-null   float64
 3   구분               1773 non-null   object
 4   장소명              1773 non-null   object
 5   소재지              1773 non-null   object
 6   Additional_Name  1773 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 110.8+ KB

In [92]:
jeju_tour = jeju_split
jeju_tour

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name
1,1,126.385364,33.470809,관광/숙박,수산유원지,제주특별자치도 제주시 애월읍 수산리 1918,.
2,2,126.771241,33.529109,관광/숙박,만장굴,제주특별자치도 제주시 구좌읍 월정리 41,"(거문오름용암동굴계)만장굴,(제주화산섬과용암동굴)만장굴"
3,3,126.941753,33.458386,관광/숙박,성산일출봉,제주특별자치도 서귀포시 성산읍 신천리 114,"일출봉,(제주화산섬과용암동굴)성산일출봉"
4,4,126.394439,33.408524,관광/숙박,제주경마공원,제주특별자치도 제주시 애월읍 소길리 1206,"경마공원,제주경마장"
5,5,126.459648,33.312044,관광/숙박,국립서귀포자연휴양림,제주특별자치도 서귀포시 대포동 산 1-1,"서귀포자연휴양림,서귀포휴양림"
...,...,...,...,...,...,...,...
3670,4915,126.432490,33.247235,관광/숙박,채움키즈풀빌라,제주특별자치도 서귀포시 대포동 779,.
3671,4916,126.694716,33.274694,관광/숙박,로드37,제주특별자치도 서귀포시 남원읍 남원리 2419-4,.
3676,4922,126.355393,33.396467,관광/숙박,제주허브캐슬,제주특별자치도 제주시 애월읍 어음리 449,.
3688,4935,126.640834,33.264269,관광/숙박,허밍제주,제주특별자치도 서귀포시 남원읍 신례리 59,.
3698,4950,126.572698,33.453664,관광/숙박,국제전기자동차엑스포,제주특별자치도 제주시 영평동 2170-1,.

# 크롤링

## 1.지역 크롤링 확인

In [10]:
import requests
from urllib.parse import quote    
import pandas as pd

In [11]:
client_id = ""
client_secret = ""

In [13]:
headers = {"X-Naver-Client-Id":client_id,"X-Naver-Client-Secret":client_secret}

In [17]:
url_base="https://openapi.naver.com/v1/search/local.json?query="
keyword = quote(input("검색 키워드를 입력하세요. : "))
url_middle="&display=10&start=1&sort=random"

url = url_base + keyword + url_middle

result = requests.get(url,headers = headers).json()                  #결과값을 변수로 지정
result                                                           #결과값 출력

{'errorMessage': 'Incorrect query request (잘못된 쿼리요청입니다.)', 'errorCode': 'SE01'}

In [18]:
result["total"]

KeyError: 'total'

## 2. 없어진 장소 처리

### 1. 숙박 업소

In [93]:
import copy
jeju_accom.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1928 entries, 0 to 3700
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       1928 non-null   int64
 1   위치좌표 X축값         1928 non-null   float64
 2   위치좌표 Y축값         1928 non-null   float64
 3   구분               1928 non-null   object
 4   장소명              1928 non-null   object
 5   소재지              1928 non-null   object
 6   Additional_Name  1928 non-null   object
dtypes: float64(2), int64(1), object(4)
memory usage: 120.5+ KB

In [94]:
jeju_accom["검색결과"] = ""
jeju_accom

C:\Users\alal8\AppData\Local\Temp/ipykernel_2372/1784111743.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  jeju_accom["검색결과"] = ""

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,0,126.495979,33.486592,관광/숙박,코리아나호텔,제주특별자치도 제주시 연동 303-10,.,
6,6,126.394730,33.273239,관광/숙박,서귀포호텔,제주특별자치도 서귀포시 상예동 161,.,
9,12,126.257018,33.222826,관광/숙박,실버스타호텔,제주특별자치도 서귀포시 대정읍 상모리 3967-13,.,
10,13,126.308401,33.229885,관광/숙박,하동민박,제주특별자치도 서귀포시 안덕면 사계리 2032-4,.,
12,15,126.335598,33.241884,관광/숙박,둥지민박,제주특별자치도 서귀포시 안덕면 화순리 804-1,.,
...,...,...,...,...,...,...,...,...
3695,4945,126.531406,33.241578,관광/숙박,돔베리조트,제주특별자치도 서귀포시 호근동 1592,.,
3696,4946,126.539649,33.517965,관광/숙박,다이아나호텔,제주특별자치도 제주시 건입동 658-1,다이아나관광호텔,
3697,4947,126.619611,33.251045,관광/숙박,바람코지게스트하우스,제주특별자치도 서귀포시 하효동 1052-3,.,
3699,5937,126.487942,33.489017,관광/숙박,케이호텔,제주특별자치도 제주시 연동 251-79,.,
3700,5938,126.519219,33.254743,관광/숙박,서귀포라마다앙코르호텔,제주특별자치도 서귀포시 서호동 1524-7,.,

In [95]:
for idx,i in jeju_accom.iterrows():
    print(idx,i["장소명"][:2])

0 코리
6 서귀
9 실버
10 하동
12 둥지
13 소라
14 산야
16 제주
17 칠십
18 아리
19 피카
20 제주
21 롯데
23 씨에
24 제주
25 제주
26 제일
27 창원
28 호텔
29 신대
30 일성
31 메가
32 드림
33 노루
34 도일
35 부영
36 제주
37 하와
38 시티
39 아산
40 MK
41 제주
42 풍년
43 한림
44 호텔
45 한성
46 제주
47 사조
49 성문
50 프린
51 성산
52 하얀
53 성진
54 빌레
56 마이
58 호텔
60 제주
62 일출
63 숙이
64 해돋
65 선샤
67 제주
70 남양
71 해변
72 노벨
73 쌍둥
74 고운
76 광령
78 산빛
79 해미
82 초록
83 뉴아
84 샤인
85 사쿠
86 베니
87 포시
88 귀빈
91 맥심
93 해피
94 아리
95 스카
96 센트
97 밀라
98 펠레
99 벤츠
100 스마
101 세광
102 유호
103 대일
104 허브
105 만년
106 라벤
107 해연
110 남문
111 꿈의
113 우리
114 금호
115 하얀
116 발리
117 가이
118 뉴신
119 리베
120 청송
121 동원
122 하남
124 유니
125 에버
126 전원
127 더호
129 명월
130 제이
131 호텔
133 호텔
134 재도
135 소피
136 제주
137 현대
138 평화
139 라임
140 서귀
141 파라
142 서귀
143 서귀
144 바닷
145 화이
148 백호
149 폭포
151 만부
152 뉴서
154 우성
155 제주
156 신세
157 나포
158 만평
159 서울
160 굿인
161 금우
162 뉴경
163 한두
164 호텔
165 강남
166 천호
167 베니
168 대림
169 남국
171 귀락
173 은하
174 대국
175 영빈
176 동명
177 대명
178 경원
180 대중
182 록산
183 썬모
184 스타
185 흥신
186 서귀
191 천제
192 큰머
193 중문
194 유정
195 남산
196 글로
197 세원
198 금오
199 그린
200 도원
201 동해
202 명신
203 경성
204 제주
207 신강
208 해마
210 오름
212 아세
213 백록
215 삼보
216 오렌
217 용천
218 금정
219 창도
220 티나
221 국일
222 호텔
223 뉴스
224 산호
225 한라
226 한진
227 서울
228 백조
229 에메
230 제주
231 호텔
232 호텔
236 레몬
238 동남
241 대아
242 알프
246 명원
248 크라
249 호텔
251 로즈
252 호텔
253 모텔
254 봉성
257 신천
258 호텔
260 갤러
261 제주
262 무궁
263 세안
264 유나
267 대동
269 남경
270 태경
271 명동
272 제주
273 제주
275 사모
276 임프
277 호텔
278 영동
279 해변
280 동천
281 호텔
282 모텔
283 탑에
284 산수
286 라마
296 제주
297 동백
298 불루
299 서부
300 솔대
302 뜨레
304 오션
305 그린
306 허니
307 제주
308 오렌
310 산타
314 섬풍
315 동성
317 에버
320 민트
321 엔젤
323 나폴
325 큰갯
328 남경
329 별장
331 뷰티
333 약천
334 황토
338 무지
339 고향
342 빨간
343 핀크
344 아로
345 팜파
348 팜힐
349 해피
351 제주
353 파인
354 에뜨
357 한아
358 풀하
362 천상
363 비하
364 클럽
365 꽃잠
366 남또
368 노을
369 바다
370 베네
371 파인
375 썬하
378 대흥
379 켄싱
381 드가
382 청솔
385 해변
386 향촌
387 바다
388 월드
391 용해
393 제주
394 밀레
396 기풍
397 올리
400 해피
401 테우
402 제주
404 신라
406 남원
407 산장
408 현대
409 한영
412 호스
414 공원
415 바다
420 제주
421 자장
423 제주
424 신신
429 제주
432 웅지
433 바다
434 코랄
435 그린
436 메이
437 제주
439 보라
440 한라
445 중문
446 뫼모
447 우리
448 초원
449 예지
451 전원
452 다정
453 레이
456 그린
457 군자
458 소닝
459 제주
461 마레
462 H3
463 돌하
464 과수
469 유리
472 시온
474 중문
475 귤향
477 꿈에
478 굿모
479 블루
480 하얀
481 올레
485 신진
486 해성
487 남쪽
488 칸델
490 전원
491 세훈
492 늘푸
493 헨젤
494 ig
495 썬콘
497 신창
498 삼다
499 스톤
502 민지
505 오렌
508 올레
510 하얀
513 제주
514 유성
515 대명
519 해변
520 힐하
522 꼬뜨
526 작은
531 제주
533 제주
535 낙원
538 초롱
542 제주
546 성산
547 성원
548 금호
549 명송
552 신양
553 해변
554 태백
555 별장
556 해촌
557 유정
558 섭지
559 토성
560 나이
561 바다
564 금강
565 귀빈
568 삼성
569 중앙
570 영일
571 동백
572 뉴월
573 대일
576 비치
577 뉴그
578 뉴그
579 한솔
581 빌레
582 와하
583 포구
584 짱구
588 안트
589 제주
590 L하
592 성산
594 제주
596 은하
597 신라
598 유림
599 현대
602 굿모
603 샤인
604 선린
605 선린
607 제주
609 오렌
610 회천
611 그린
612 한솔
613 늘푸
619 초록
622 JJ
623 작은
625 제주
628 초가
634 필리
635 해오
636 에메
637 제주
638 제주
639 오아
640 씨월
641 리빙
642 제주
644 모노
645 레드
646 풀하
647 녹원
655 돌하
657 코지
658 이쁜
659 예함
660 백록
661 밀파
662 꿈의
665 낭구
668 노블
669 오름
671 혼인
672 일출
673 성산
674 일출
675 바닷
691 삼해
693 동굴
694 섬사
695 해돋
696 바다
698 홍조
699 우도
700 대마
703 경성
704 지현
705 썬비
706 백악
708 등머
710 제주
713 카사
714 작은
716 신성
717 테마
718 발리
719 동경
720 퀸호
721 샤뜰
724 노블
725 한란
726 오리
727 호텔
728 탑모
729 호텔
730 대구
731 모텔
732 금산
733 에메
734 엘루
739 에버
740 테마
741 예다
742 오션
743 상지
744 벨레
745 경신
749 위너
750 뉴월
751 캐피
754 제주
755 제주
756 뉴코
757 모텔
758 프린
759 피닉
760 미래
761 해피
762 아로
763 조은
764 호텔
765 모텔
766 아이
767 제주
768 썬랜
769 라자
770 뉴제
771 스위
772 헤럴
773 호텔
774 오피
777 호텔
779 한라
780 동양
781 해아
782 비오
783 오병
784 솔베
785 한신
788 호도
789 아리
796 타미
801 하늘
802 곽지
805 우뚜
806 통나
808 몽마
810 쉴만
811 블랙
812 솔동
813 제주
814 제주
815 아라
819 이모
822 한림
823 우리
825 코지
826 일성
827 제주
828 제주
830 상예
832 마린
833 재즈
837 해누
839 생수
846 차귀
849 갯바
852 논짓
853 드림
855 늘바
856 바당
858 모텔
859 해안
861 미르
863 오션
866 중문
868 과원
871 윈드
872 준하
873 아파
874 모네
875 하도
878 하고
879 스머
880 중문
881 지삿
883 하일
885 하바
886 뉴제
888 해안
889 그랑
890 유니
893 제주
895 펄팜
897 바닷
898 송악
899 남강
900 카이
901 바닷
902 산방
903 산방
905 동원
906 스카
907 아로
909 제주
911 로즈
912 메이
916 비치
918 바다
919 제주
921 오아
922 정화
923 동굴
924 소섬
925 전원
927 숙데
929 일성
930 조은
935 블루
938 낭펜
944 제주
945 억새
946 화성
947 섭지
948 영민
952 제주
953 제주
957 용궁
958 토마
961 푸른
962 성산
964 C&
965 자연
967 연하
968 에뜨
972 팔도
973 남촌
975 제주
976 휴민
981 금호
984 삼천
990 그린
991 제주
992 더하
995 J하
1006 오션
1143 제주
1146 제주
1149 파멜
1150 뉴맨
1151 국제
1152 이호
1156 내도
1158 블루
1159 삼다
1160 내파
1162 노인
1163 대유
1169 유수
1171 오렌
1173 아뜨
1174 돌과
1177 아름
1178 산초
1182 그리
1183 로그
1186 이호
1187 별마
1188 플로
1189 제주
1192 블루
1193 씨포
1195 이어
1196 하와
1197 호텔
1201 미래
1203 팡라
1204 바이
1205 렛츠
1206 바다
1207 마리
1208 신흥
1211 펜션
1212 지중
1213 신혼
1215 아림
1216 제주
1217 파스
1218 매직
1220 제주
1221 명진
1223 샤토
1225 현웅
1226 여울
1230 아시
1231 섬사
1232 주얼
1233 뜨레
1234 호텔
1235 노블
1237 제주
1238 블라
1241 제주
1244 수라
1248 현정
1251 소낭
1252 방파
1255 선린
1256 선린
1259 선린
1261 휴양
1265 포유
1267 하늘
1268 선화
1274 사계
1275 하추
1277 묵리
1278 이부
1280 대물
1281 추자
1284 물둘
1285 황제
1286 성보
1288 여정
1289 파도
1293 나바
1294 별장
1295 팔도
1296 부산
1297 마라
1299 온천
1302 모텔
1303 메모
1304 골드
1305 허니
1308 남미
1310 펜션
1313 코코
1316 유러
1320 포시
1323 제주
1325 해광
1327 좋은
1328 제주
1330 문화
1333 호텔
1334 금성
1336 호텔
1339 서울
1340 럭키
1343 검은
1344 썬베
1349 정다
1351 바다
1353 호텔
1355 선인
1356 하얀
1357 위드
1358 멜케
1359 바다
1361 월드
1362 기린
1366 장수
1369 영성
1370 제주
1371 모아
1374 란펜
1378 올인
1379 영신
1381 트윈
1382 비원
1383 루마
1392 해송
1393 으뜸
1394 바람
1395 이앤
1400 그림
1402 실크
1404 오름
1407 타워
1409 똘똘
1411 우사
1412 호텔
1413 은정
1414 윤철
1415 대식
1416 관식
1417 현주
1418 승우
1419 용성
1421 뜰안
1422 삼다
1430 하늘
1431 산호
1432 우도
1433 태성
1435 산물
1437 우리
1438 화순
1441 서광
1442 연지
1443 명신
1444 다정
1445 경화
1446 하림
1447 풍기
1448 산바
1453 더제
1455 새콤
1456 모리
1464 바다
1465 빌로
1466 연화
1476 제주
1477 해변
1478 디셈
1479 제주
1480 로그
1481 외도
1488 조이
1493 경림
1499 고도
1504 궁궐
1505 귀덕
1506 그린
1507 금나
1508 나래
1511 다보
1512 다정
1514 대풍
1519 동수
1520 동은
1522 락희
1523 리버
1524 마니
1527 명진
1529 백록
1532 사랑
1534 사시
1539 서귀
1540 선린
1546 수지
1547 신동
1549 씨하
1551 애니
1552 야베
1563 어촌
1564 어촌
1569 영도
1570 영보
1571 오노
1572 옥륜
1574 용머
1575 우성
1577 월드
1578 이어
1579 일출
1580 자유
1583 하이
1585 준성
1593 봄그
1596 대웅
1623 이채
1629 제주
1637 아미
1639 혜지
1640 산림
1641 영동
1643 야성
1644 광주
1645 제주
1646 한라
1653 해녀
1656 올래
1657 고향
1658 탐라
1659 주예
1661 바다
1662 해변
1663 괸당
1665 펜션
1666 E좋
1668 등대
1673 올레
1686 마라
1687 해돋
1689 해변
1690 바리
1691 한라
1692 초원
1693 청해
1694 꿈에
1701 비양
1702 별빛
1705 사계
1706 제주
1707 강원
1708 아리
1711 이모
1712 협재
1713 바닷
1714 해변
1715 제천
1716 수정
1718 고향
1719 탑C
1724 그린
1735 오라
1737 낙원
1740 홍도
1741 섭지
1742 사라
1744 오름
1745 샛별
1746 ok
1747 조아
1748 귤림
1749 숲섬
1755 효도
1758 산수
1759 바다
1760 리슈
1761 서라
1762 탐라
1763 장수
1764 백록
1766 은성
1767 영림
1768 반도
1769 송원
1770 한양
1771 크라
1784 신양
1789 미앤
1790 JJ
1791 더아
1792 중문
1804 푸른
1805 초록
1806 오라
1811 팽나
1818 신흥
1820 더뷰
1825 빌레
1833 궁전
1834 숲속
1836 월정
1837 대림
1838 약속
1839 대호
1847 팔도
1848 큰엉
1850 일출
1851 영풍
1852 호텔
1853 아람
1854 별장
1855 아트
1856 버킹
1857 신제
1858 연동
1859 금호
1860 무진
1866 스타
1868 덕산
1870 황제
1874 제주
1879 나인
1880 담앤
1881 풍림
1885 한라
1887 제주
1888 행복
1889 오성
1892 앙크
1893 중문
1894 둥지
1895 종원
1899 해성
1900 호텔
1902 조은
1906 아망
1908 다솜
1909 로멘
1911 힐파
1912 피카
1913 투데
1916 나들
1917 롯데
1921 가정
1922 하늘
1925 럭키
1926 서남
1928 현대
1929 우리
1931 블루
1932 완도
1933 해변
1934 더갤
1935 길섶
1943 가고
1945 선린
1947 비엔
1950 영빈
1951 글로
1952 크로
1953 용연
1954 제주
1955 아름
1956 쌈지
1957 안동
1961 빛이
1962 우리
1964 장전
1965 애니
1966 타이
1967 파크
1970 오손
1973 뉴오
1974 제주
1975 제주
1976 황토
1977 대정
1978 진영
1980 군호
1981 성큼
1982 산방
1983 경치
1984 상동
1985 용해
1986 산방
1987 대정
1988 최남
1989 서바
1990 한반
1991 제일
1992 나무
1993 요트
1997 희정
1998 유정
1999 등대
2008 고운
2010 쉼터
2011 동부
2012 미소
2016 대평
2017 대동
2018 아모
2024 중문
2026 에이
2027 해피
2030 일출
2031 팜밸
2032 비울
2033 제주
2037 윈리
2038 야스
2039 다솜
2045 고시
2046 윈드
2047 윈드
2048 해오
2058 서우
2063 부영
2064 제주
2070 조이
2071 정글
2072 소라
2075 올레
2078 미라
2079 해안
2080 도두
2082 스카
2083 소낭
2084 오름
2089 탐라
2091 대평
2092 올레
2094 포토
2097 백사
2098 삼다
2099 이어
2100 그레
2101 난드
2105 아덴
2106 올림
2108 중문
2111 저지
2112 들매
2114 안나
2117 글라
2118 애월
2123 대박
2132 불란
2133 사이
2134 가원
2149 대정
2153 휴림
2159 뽄쟁
2165 한가
2167 체리
2170 로뎀
2171 우도
2172 제주
2176 빅하
2180 장원
2181 닐펜
2183 제주
2184 빌라
2185 새집
2187 올레
2190 모나
2191 이호
2195 한라
2196 초록
2197 유모
2199 보오
2202 리치
2204 에코
2210 용두
2211 용오
2214 쉼터
2217 한라
2219 포구
2221 호반
2222 진미
2224 비둘
2225 세림
2227 가완
2230 오렌
2231 성산
2232 일출
2234 밀라
2236 예하
2237 서라
2238 덕원
2239 그린
2243 도로
2245 동남
2246 해비
2247 성일
2248 헤라
2249 류림
2250 마주
2251 남일
2252 시드
2253 썬시
2254 할망
2255 올레
2256 한라
2258 해오
2260 하얀
2261 게스
2262 바당
2264 터미
2267 쿨쿨
2272 동산
2273 카멜
2275 제주
2278 메모
2292 롯데
2294 제주
2295 두나
2296 셋째
2297 라퓨
2298 월드
2304 성산
2307 호텔
2308 노꼬
2309 초콜
2310 스토
2312 고려
2315 1박
2316 청아
2317 파도
2318 그린
2319 등대
2320 별장
2321 OK
2322 더게
2324 예래
2325 W모
2326 씨스
2327 하늘
2329 네이
2331 전망
2334 같이
2335 자인
2337 팽나
2338 메이
2339 안게
2341 인게
2342 토마
2345 가파
2346 바다
2347 우리
2348 산방
2349 달콤
2353 올레
2356 일선
2357 한담
2358 제주
2359 하얀
2360 맨도
2361 여래
2362 오성
2365 돌빌
2366 글로
2367 바다
2368 동천
2383 줄리
2385 함덕
2386 남국
2387 서로
2388 요셉
2390 비빔
2391 두리
2393 뽀요
2394 세인
2396 비체
2397 우도
2398 아프
2399 함덕
2400 필링
2401 안전
2404 문주
2406 신양
2408 레몬
2409 태흥
2410 블루
2411 훈이
2412 금바
2413 아름
2456 제주
2457 제주
2459 봄꽃
2461 짝게
2462 루멘
2463 길하
2464 제니
2471 빨강
2473 레프
2474 제주
2479 또올
2481 달팽
2482 포도
2483 산방
2484 안녕
2487 치엘
2488 쉴띠
2489 차귀
2490 슬리
2492 율게
2495 그린
2497 금능
2498 꼼지
2499 제주
2500 봄날
2501 시후
2502 알토
2503 또올
2504 사계
2505 오멍
2506 아이
2507 삼달
2508 안녕
2509 숨게
2510 파슬
2512 더파
2515 악당
2516 육삼
2518 후스
2519 송정
2520 두그
2522 단빌
2531 한림
2534 가자
2537 제주
2538 호스
2539 게스
2541 꿈꾸
2542 그린
2544 해적
2546 소소
2547 젠게
2548 오션
2549 허당
2550 자유
2551 여울
2552 이응
2553 스마
2554 마리
2555 공1
2556 미쓰
2557 찬타
2558 룸바
2562 휴먼
2565 M게
2567 드림
2568 상도
2570 담게
2572 달빛
2573 온더
2574 벤촌
2575 네모
2579 게스
2584 한라
2586 뿌리
2587 중문
2588 숨비
2590 데이
2591 반디
2592 게스
2593 빨간
2594 제주
2595 사계
2596 게으
2597 제푸
2599 해바
2628 트리
2646 사려
2647 조이
2655 방울
2657 이안
2658 흰고
2659 제주
2660 안뜨
2661 위더
2663 아름
2664 솔숲
2666 해성
2669 이린
2670 제주
2674 선돌
2675 엘로
2676 꿈꾸
2678 탐라
2679 길라
2680 하이
2681 카이
2683 빌라
2684 제주
2685 백록
2689 돌담
2690 현게
2691 유화
2692 코리
2693 파인
2697 지중
2698 중문
2699 해비
2700 소고
2702 게스
2703 Un
2704 제주
2706 씨스
2707 올리
2710 풍경
2711 진주
2712 곽지
2717 스카
2718 버킹
2719 엘린
2720 섬민
2724 아라
2725 해다
2726 아랑
2727 바다
2728 한영
2729 오케
2730 라헨
2733 정훈
2734 월드
2735 경순
2736 월정
2739 엘리
2745 도일
2746 통나
2759 스타
2761 함덕
2762 리조
2768 선흘
2769 한일
2772 미라
2773 포유
2774 비양
2775 파도
2778 구엄
2779 용진
2781 항구
2783 월정
2787 한국
2791 씨앤
2793 포천
2795 함덕
2796 해피
2797 일성
2798 똘똘
2799 일출
2804 오션
2805 윈드
2806 더갤
2807 드림
2808 제주
2809 제주
2811 신가
2812 탐라
2813 바다
2815 아모
2817 헌스
2819 다섯
2821 바이
2822 수평
2825 스카
2827 일신
2829 하니
2830 제주
2831 제일
2833 향나
2836 제주
2837 섬민
2839 백록
2842 크리
2844 하얀
2846 흥진
2847 힐링
2848 올레
2851 김녕
2852 바다
2853 준게
2854 나뜨
2857 엠게
2858 해변
2859 도두
2860 초록
2861 씨티
2862 MK
2863 애니
2864 해피
2865 센트
2866 샵모
2867 U모
2868 마이
2869 제주
2874 모텔
2875 오피
2876 가까
2879 비오
2882 J하
2883 산지
2885 그리
2887 블루
2895 미래
2903 해변
2904 비치
2905 주얼
2925 해녀
2926 별관
2927 타워
2929 명원
2930 재호
2932 차귀
2935 바다
2936 혜성
2938 정치
2939 애리
2941 레인
2942 대장
2943 쁘띠
2946 올레
2947 영주
2948 에이
2950 성풍
2951 객의
2952 상록
2954 Go
2958 폴리
2959 내올
2960 솔향
2963 산지
2964 경원
2965 양지
2966 동아
2968 레지
2970 초콜
2971 호텔
2972 백호
2973 오리
2974 AT
2977 민박
2978 제주
2979 광스
2980 토마
2981 노노
2982 올레
2983 스토
2987 제주
2988 엠제
2989 토리
2990 두지
2991 예그
2992 유앤
2993 동그
2994 바다
2995 펠리
2997 하얀
2998 서귀
2999 만나
3000 미도
3001 쏠레
3003 자홍
3004 중앙
3005 서라
3008 동원
3009 대우
3011 팜스
3012 제주
3014 귤익
3015 황토
3019 포그
3022 제이
3023 아름
3025 장수
3026 펠리
3027 바다
3029 동베
3038 동산
3040 천혜
3041 사이
3051 이가
3052 이가
3055 태흥
3056 3번
3067 대평
3074 신라
3075 사이
3081 제주
3083 팜비
3084 영빈
3085 정실
3093 골드
3096 우리
3100 신성
3101 신성
3102 유로
3103 유로
3104 유로
3105 유로
3106 유로
3107 유로
3108 유로
3109 유로
3110 조은
3111 조은
3112 조은
3113 중문
3116 곰민
3117 송악
3118 송악
3119 송악
3120 송악
3121 송악
3124 혼섬
3125 대청
3126 산바
3127 설큼
3128 사계
3133 꼬닥
3134 백패
3135 헤라
3136 성산
3138 썬게
3140 훼밀
3141 유한
3144 남양
3146 오소
3147 큰낭
3152 동일
3153 영원
3154 대정
3155 해안
3156 진영
3157 고성
3159 바다
3161 넙빌
3165 귤하
3166 금모
3167 노을
3169 돔그
3170 바당
3172 쇠소
3175 에코
3176 펜션
3179 갯바
3180 올레
3181 하바
3184 산야
3187 올레
3190 대정
3191 누리
3192 강정
3193 중문
3194 큰갯
3195 논짓
3196 중문
3198 호텔
3199 태공
3200 에이
3202 은하
3208 제주
3210 소라
3211 유러
3213 낙원
3217 고망
3219 오소
3221 섭지
3222 라사
3223 올레
3226 올인
3228 아로
3231 귤향
3232 남쪽
3234 제주
3238 강변
3239 해비
3241 제주
3247 눈오
3249 게스
3250 나라
3253 코델
3254 바당
3255 일출
3256 고향
3258 환이
3261 코스
3262 오성
3263 일미
3264 호스
3265 제주
3266 옐로
3269 금학
3271 알뜨
3275 JI
3276 섬뜰
3277 웨스
3279 반딧
3280 방듸
3281 바우
3283 보네
3285 사랑
3286 바다
3289 연우
3291 구름
3292 숲섬
3294 공천
3295 쉼팡
3296 풍경
3298 나무
3300 타시
3301 동양
3302 유성
3303 CF
3304 천일
3305 하나
3306 대아
3307 장원
3308 행복
3309 호텔
3312 공원
3313 대원
3314 수와
3315 배비
3321 광성
3322 광명
3323 무지
3324 흥진
3326 한옥
3327 용운
3328 대영
3331 이레
3332 성림
3334 보영
3335 만복
3336 마라
3337 황제
3338 정성
3339 M모
3340 동양
3341 모텔
3342 남일
3343 우수
3344 청오
3345 탐라
3347 호텔
3349 명동
3352 덕수
3353 소라
3354 안남
3356 올림
3357 숨게
3358 타원
3359 바위
3361 용연
3363 신라
3364 대성
3365 삼흥
3368 샬롬
3369 바당
3370 제주
3371 제주
3372 J팜
3373 삼보
3374 화음
3376 토스
3377 라벤
3378 파미
3380 호텔
3382 까사
3384 수필
3386 테디
3387 엠버
3388 제주
3389 바당
3390 포트
3391 동막
3392 홍익
3394 귤낭
3395 행운
3396 펠리
3399 제주
3400 인연
3402 산타
3403 에덴
3405 예예
3406 아다
3407 짝게
3408 강남
3409 스윗
3411 호텔
3412 해모
3413 사려
3414 게스
3415 개스
3416 제주
3417 소리
3420 로긴
3421 오슬
3422 싸이
3423 빠담
3425 힐링
3426 커플
3427 쪼인
3428 쥬빌
3429 타오
3430 엠제
3431 아임
3432 라임
3433 큰엉
3438 행복
3439 켄싱
3440 보리
3441 제주
3444 컨츄
3445 엉클
3446 콤마
3447 오아
3448 오누
3449 해호
3452 뉴그
3454 블루
3455 제주
3456 레브
3457 에이
3458 절물
3459 제주
3460 힐링
3461 에바
3462 하늘
3463 올레
3464 제주
3465 씨앤
3466 아모
3468 더레
3469 계란
3470 제주
3472 더포
3473 그라
3475 홍익
3476 섬이
3477 하이
3479 펄리
3480 샹그
3482 라포
3483 제마
3484 고추
3486 베니
3487 이비
3488 헤라
3489 준그
3490 힐하
3491 드라
3492 호텔
3494 핑크
3497 써니
3498 길게
3499 바우
3500 호텔
3501 순덕
3502 샤이
3503 단디
3504 도시
3506 성사
3510 마당
3511 제주
3513 라온
3514 라만
3515 라파
3516 남빌
3519 성산
3520 챨스
3524 R&
3525 메이
3526 솔향
3528 셀라
3529 아이
3530 제주
3531 새섬
3532 바끄
3534 디아
3537 풀향
3538 게스
3539 아일
3542 산방
3544 더올
3545 르페
3548 거문
3549 포안
3550 달끝
3551 돈내
3552 파더
3553 제주
3554 도레
3559 호텔
3560 비아
3561 더스
3563 고팡
3565 더머
3566 불란
3567 고스
3568 담모
3569 로뎀
3571 게스
3572 오랑
3574 11
3575 테너
3577 하루
3578 마더
3579 해와
3580 그린
3582 루체
3583 프라
3584 자연
3585 마따
3586 가가
3587 제이
3588 감비
3590 파더
3591 부자
3592 루스
3593 강가
3594 나인
3595 하모
3596 자주
3597 하늘
3598 제주
3599 끄라
3600 바다
3602 파밀
3603 썬민
3604 가정
3605 허브
3606 더코
3607 제주
3608 여유
3611 나날
3612 제이
3613 올레
3615 히든
3616 비투
3617 안브
3618 제주
3621 아리
3623 휴양
3625 휴양
3626 제주
3627 금룡
3628 오션
3629 제니
3630 JJ
3633 더하
3634 스카
3635 호텔
3636 천마
3637 이그
3638 윈드
3639 하울
3640 캘리
3641 제주
3643 바다
3644 솔바
3646 더비
3647 비움
3648 아미
3649 섬이
3650 중문
3653 씨제
3654 이화
3655 라메
3656 오렌
3657 수앤
3658 슈네
3659 비롯
3660 아스
3663 고래
3664 녹원
3665 유리
3666 그림
3667 샤이
3669 선스
3672 제주
3673 엠버
3674 굿데
3675 햇살
3677 펜션
3678 케이
3679 로즈
3680 세인
3681 제주
3682 오라
3683 중문
3684 콤마
3685 천제
3686 패밀
3687 더럭
3689 린앤
3690 설문
3691 소리
3692 무명
3693 지수
3694 풍경
3695 돔베
3696 다이
3697 바람
3699 케이
3700 서귀

In [96]:
import time 
for idx,i in jeju_accom.iterrows():
    time.sleep(1.3)
    if len(i["장소명"]) > 2: 
        if i["장소명"][:2] == "제주":
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote(i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                jeju_accom.loc[idx, "검색결과"] = "없는 장소"
        else:
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote("제주" + i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                jeju_accom.loc[idx, "검색결과"] = "없는 장소"
    else:
        url_base="https://openapi.naver.com/v1/search/local.json?query="
        keyword = quote("제주" + i["장소명"])
        url_middle="&display=5 & start=1"
        url = url_base + keyword + url_middle
        result = requests.get(url,headers = headers).json()
        if result["total"] == 0:
                jeju_accom.loc[idx, "검색결과"] = "없는 장소"

C:\Users\alal8\miniconda3\envs\ds_study\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [97]:
len(jeju_accom[jeju_accom["검색결과"] =="없는 장소"])

627

In [98]:
jeju_accom

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,0,126.495979,33.486592,관광/숙박,코리아나호텔,제주특별자치도 제주시 연동 303-10,.,
6,6,126.394730,33.273239,관광/숙박,서귀포호텔,제주특별자치도 서귀포시 상예동 161,.,
9,12,126.257018,33.222826,관광/숙박,실버스타호텔,제주특별자치도 서귀포시 대정읍 상모리 3967-13,.,
10,13,126.308401,33.229885,관광/숙박,하동민박,제주특별자치도 서귀포시 안덕면 사계리 2032-4,.,없는 장소
12,15,126.335598,33.241884,관광/숙박,둥지민박,제주특별자치도 서귀포시 안덕면 화순리 804-1,.,
...,...,...,...,...,...,...,...,...
3695,4945,126.531406,33.241578,관광/숙박,돔베리조트,제주특별자치도 서귀포시 호근동 1592,.,
3696,4946,126.539649,33.517965,관광/숙박,다이아나호텔,제주특별자치도 제주시 건입동 658-1,다이아나관광호텔,
3697,4947,126.619611,33.251045,관광/숙박,바람코지게스트하우스,제주특별자치도 서귀포시 하효동 1052-3,.,없는 장소
3699,5937,126.487942,33.489017,관광/숙박,케이호텔,제주특별자치도 제주시 연동 251-79,.,
3700,5938,126.519219,33.254743,관광/숙박,서귀포라마다앙코르호텔,제주특별자치도 서귀포시 서호동 1524-7,.,

In [104]:
jeju_accom = jeju_accom.drop(jeju_accom[jeju_accom["검색결과"]=="없는 장소"].index)

In [105]:
jeju_accom

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,0,126.495979,33.486592,관광/숙박,코리아나호텔,제주특별자치도 제주시 연동 303-10,.,
6,6,126.394730,33.273239,관광/숙박,서귀포호텔,제주특별자치도 서귀포시 상예동 161,.,
9,12,126.257018,33.222826,관광/숙박,실버스타호텔,제주특별자치도 서귀포시 대정읍 상모리 3967-13,.,
12,15,126.335598,33.241884,관광/숙박,둥지민박,제주특별자치도 서귀포시 안덕면 화순리 804-1,.,
13,16,126.337773,33.240317,관광/숙박,소라민박,제주특별자치도 서귀포시 안덕면 화순리 448,.,
...,...,...,...,...,...,...,...,...
3694,4944,126.553742,33.244845,관광/숙박,풍경호텔,제주특별자치도 서귀포시 서홍동 586,풍경관광호텔,
3695,4945,126.531406,33.241578,관광/숙박,돔베리조트,제주특별자치도 서귀포시 호근동 1592,.,
3696,4946,126.539649,33.517965,관광/숙박,다이아나호텔,제주특별자치도 제주시 건입동 658-1,다이아나관광호텔,
3699,5937,126.487942,33.489017,관광/숙박,케이호텔,제주특별자치도 제주시 연동 251-79,.,
3700,5938,126.519219,33.254743,관광/숙박,서귀포라마다앙코르호텔,제주특별자치도 서귀포시 서호동 1524-7,.,

### 2. 관광지

In [106]:
jeju_tour["검색결과"] = ""
jeju_tour

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
1,1,126.385364,33.470809,관광/숙박,수산유원지,제주특별자치도 제주시 애월읍 수산리 1918,.,
2,2,126.771241,33.529109,관광/숙박,만장굴,제주특별자치도 제주시 구좌읍 월정리 41,"(거문오름용암동굴계)만장굴,(제주화산섬과용암동굴)만장굴",
3,3,126.941753,33.458386,관광/숙박,성산일출봉,제주특별자치도 서귀포시 성산읍 신천리 114,"일출봉,(제주화산섬과용암동굴)성산일출봉",
4,4,126.394439,33.408524,관광/숙박,제주경마공원,제주특별자치도 제주시 애월읍 소길리 1206,"경마공원,제주경마장",
5,5,126.459648,33.312044,관광/숙박,국립서귀포자연휴양림,제주특별자치도 서귀포시 대포동 산 1-1,"서귀포자연휴양림,서귀포휴양림",
...,...,...,...,...,...,...,...,...
3670,4915,126.432490,33.247235,관광/숙박,채움키즈풀빌라,제주특별자치도 서귀포시 대포동 779,.,
3671,4916,126.694716,33.274694,관광/숙박,로드37,제주특별자치도 서귀포시 남원읍 남원리 2419-4,.,
3676,4922,126.355393,33.396467,관광/숙박,제주허브캐슬,제주특별자치도 제주시 애월읍 어음리 449,.,
3688,4935,126.640834,33.264269,관광/숙박,허밍제주,제주특별자치도 서귀포시 남원읍 신례리 59,.,
3698,4950,126.572698,33.453664,관광/숙박,국제전기자동차엑스포,제주특별자치도 제주시 영평동 2170-1,.,

In [107]:
import time 
for idx,i in jeju_tour.iterrows():
    time.sleep(1.5)
    if len(i["장소명"]) > 2: 
        if i["장소명"][:2] == "제주":
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote(i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                jeju_tour.loc[idx, "검색결과"] = "없는 장소"
        else:
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote("제주" + i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                jeju_tour.loc[idx, "검색결과"] = "없는 장소"
    else:
        url_base="https://openapi.naver.com/v1/search/local.json?query="
        keyword = quote("제주" + i["장소명"])
        url_middle="&display=5 & start=1"
        url = url_base + keyword + url_middle
        result = requests.get(url,headers = headers).json()
        if result["total"] == 0:
                jeju_tour.loc[idx, "검색결과"] = "없는 장소"

In [108]:
len(jeju_tour[jeju_tour["검색결과"] =="없는 장소"])

565

In [109]:
jeju_tour = jeju_tour.drop(jeju_tour[jeju_tour["검색결과"]=="없는 장소"].index)

In [110]:
jeju_tour

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
1,1,126.385364,33.470809,관광/숙박,수산유원지,제주특별자치도 제주시 애월읍 수산리 1918,.,
2,2,126.771241,33.529109,관광/숙박,만장굴,제주특별자치도 제주시 구좌읍 월정리 41,"(거문오름용암동굴계)만장굴,(제주화산섬과용암동굴)만장굴",
3,3,126.941753,33.458386,관광/숙박,성산일출봉,제주특별자치도 서귀포시 성산읍 신천리 114,"일출봉,(제주화산섬과용암동굴)성산일출봉",
4,4,126.394439,33.408524,관광/숙박,제주경마공원,제주특별자치도 제주시 애월읍 소길리 1206,"경마공원,제주경마장",
7,7,126.321849,33.252499,관광/숙박,제주조각공원,제주특별자치도 서귀포시 안덕면 덕수리 산 27,조각공원,
...,...,...,...,...,...,...,...,...
3662,4907,126.393513,33.484274,관광/숙박,티앤유,제주특별자치도 제주시 애월읍 하귀2리 2693-3,.,
3668,4913,126.857562,33.403382,관광/숙박,제주맨도롱,제주특별자치도 서귀포시 성산읍 난산리 1835,.,
3670,4915,126.432490,33.247235,관광/숙박,채움키즈풀빌라,제주특별자치도 서귀포시 대포동 779,.,
3671,4916,126.694716,33.274694,관광/숙박,로드37,제주특별자치도 서귀포시 남원읍 남원리 2419-4,.,
3698,4950,126.572698,33.453664,관광/숙박,국제전기자동차엑스포,제주특별자치도 제주시 영평동 2170-1,.,

### 3.동식물원

In [111]:
park = pd.read_excel("POI_공원_산_동.식물원.xlsx")
park.head()

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name
0,10,126.414441,33.252417,공원/산/동.식물원,제주여미지식물원,제주특별자치도 서귀포시 색달동 2920,"제주도관광식물원,제주관광식물원,여미지식물원"
1,19,126.255053,33.325573,공원/산/동.식물원,생각하는정원,제주특별자치도 제주시 한경면 저지리 1534,분재예술원(구)
2,75,126.238428,33.390257,공원/산/동.식물원,한림공원,제주특별자치도 제주시 한림읍 협재리 2644,.
3,121,126.492892,33.469378,공원/산/동.식물원,한라수목원,제주특별자치도 제주시 연동 1000,.
4,186,126.491429,33.491767,공원/산/동.식물원,삼무공원,제주특별자치도 제주시 연동 270-5,베두리오름

In [112]:
park["검색결과"] = ""
park.head()

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,10,126.414441,33.252417,공원/산/동.식물원,제주여미지식물원,제주특별자치도 서귀포시 색달동 2920,"제주도관광식물원,제주관광식물원,여미지식물원",
1,19,126.255053,33.325573,공원/산/동.식물원,생각하는정원,제주특별자치도 제주시 한경면 저지리 1534,분재예술원(구),
2,75,126.238428,33.390257,공원/산/동.식물원,한림공원,제주특별자치도 제주시 한림읍 협재리 2644,.,
3,121,126.492892,33.469378,공원/산/동.식물원,한라수목원,제주특별자치도 제주시 연동 1000,.,
4,186,126.491429,33.491767,공원/산/동.식물원,삼무공원,제주특별자치도 제주시 연동 270-5,베두리오름,

In [113]:
import time 
for idx,i in park.iterrows():
    time.sleep(1.5)
    if len(i["장소명"]) > 2: 
        if i["장소명"][:2] == "제주":
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote(i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                park.loc[idx, "검색결과"] = "없는 장소"
        else:
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote("제주" + i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                park.loc[idx, "검색결과"] = "없는 장소"
    else:
        url_base="https://openapi.naver.com/v1/search/local.json?query="
        keyword = quote("제주" + i["장소명"])
        url_middle="&display=5 & start=1"
        url = url_base + keyword + url_middle
        result = requests.get(url,headers = headers).json()
        if result["total"] == 0:
                park.loc[idx, "검색결과"] = "없는 장소"

In [114]:
len(park[park["검색결과"] =="없는 장소"])

50

In [127]:
park = park.drop(park[park["검색결과"]=="없는 장소"].index)
park

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,10,126.414441,33.252417,공원/산/동.식물원,제주여미지식물원,제주특별자치도 서귀포시 색달동 2920,"제주도관광식물원,제주관광식물원,여미지식물원",
1,19,126.255053,33.325573,공원/산/동.식물원,생각하는정원,제주특별자치도 제주시 한경면 저지리 1534,분재예술원(구),
2,75,126.238428,33.390257,공원/산/동.식물원,한림공원,제주특별자치도 제주시 한림읍 협재리 2644,.,
3,121,126.492892,33.469378,공원/산/동.식물원,한라수목원,제주특별자치도 제주시 연동 1000,.,
4,186,126.491429,33.491767,공원/산/동.식물원,삼무공원,제주특별자치도 제주시 연동 270-5,베두리오름,
...,...,...,...,...,...,...,...,...
202,4397,126.640996,33.265219,공원/산/동.식물원,공천포쉼터,제주특별자치도 서귀포시 남원읍 신례리 92-4,.,
203,4411,126.544912,33.502333,공원/산/동.식물원,어린이공원,제주특별자치도 제주시 일도이동 65,.,
206,4686,126.323022,33.348130,공원/산/동.식물원,새미은총의동산,제주특별자치도 제주시 한림읍 금악리 365-1,.,
207,4726,126.345371,33.310118,공원/산/동.식물원,IUCN기념숲,제주특별자치도 서귀포시 안덕면 동광리 795-1,.,
208,4788,126.275076,33.356162,공원/산/동.식물원,제주비블리아성서식물원,제주특별자치도 제주시 한림읍 상명리 1191-5,"비블리아성서식물원,성서식물원",

### 4.레저/스포츠

In [116]:
leisure = pd.read_excel("POI_레져_스포츠.xlsx")
leisure.head()

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name
0,17,126.333311,33.240267,레져/스포츠,화순금모래해변,제주특별자치도 서귀포시 안덕면 화순리 776-8,화순금모래해수욕장
1,21,126.453287,33.286064,레져/스포츠,트레블러스호텔승마장,제주특별자치도 서귀포시 대포동 1-1,에덴승마장
2,23,126.394655,33.277406,레져/스포츠,대유수렵장,제주특별자치도 서귀포시 상예동 144,.
3,25,126.393129,33.314993,레져/스포츠,핀크스골프클럽(퍼블릭),제주특별자치도 서귀포시 안덕면 상천리 산 62-3,"핀크스GC(퍼블릭),핀크스골프장(퍼블릭),SK핀크스골프클럽(퍼블릭)"
4,31,126.405742,33.245084,레져/스포츠,하얏트리젠시제주수영장,제주특별자치도 서귀포시 색달동 3039-1,"하얏트호텔제주수영장,제주하얏트호텔수영장,하얏트호텔수영장"

In [117]:
leisure["검색결과"] = ""
leisure.head()

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,17,126.333311,33.240267,레져/스포츠,화순금모래해변,제주특별자치도 서귀포시 안덕면 화순리 776-8,화순금모래해수욕장,
1,21,126.453287,33.286064,레져/스포츠,트레블러스호텔승마장,제주특별자치도 서귀포시 대포동 1-1,에덴승마장,
2,23,126.394655,33.277406,레져/스포츠,대유수렵장,제주특별자치도 서귀포시 상예동 144,.,
3,25,126.393129,33.314993,레져/스포츠,핀크스골프클럽(퍼블릭),제주특별자치도 서귀포시 안덕면 상천리 산 62-3,"핀크스GC(퍼블릭),핀크스골프장(퍼블릭),SK핀크스골프클럽(퍼블릭)",
4,31,126.405742,33.245084,레져/스포츠,하얏트리젠시제주수영장,제주특별자치도 서귀포시 색달동 3039-1,"하얏트호텔제주수영장,제주하얏트호텔수영장,하얏트호텔수영장",

In [118]:
import time 
for idx,i in leisure.iterrows():
    time.sleep(1.5)
    if len(i["장소명"]) > 2: 
        if i["장소명"][:2] == "제주":
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote(i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                leisure.loc[idx, "검색결과"] = "없는 장소"
        else:
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote("제주" + i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                leisure.loc[idx, "검색결과"] = "없는 장소"
    else:
        url_base="https://openapi.naver.com/v1/search/local.json?query="
        keyword = quote("제주" + i["장소명"])
        url_middle="&display=5 & start=1"
        url = url_base + keyword + url_middle
        result = requests.get(url,headers = headers).json()
        if result["total"] == 0:
                leisure.loc[idx, "검색결과"] = "없는 장소"

In [119]:
len(leisure[leisure["검색결과"] =="없는 장소"])

265

In [128]:
leisure = leisure.drop(leisure[leisure["검색결과"]=="없는 장소"].index)
leisure

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,17,126.333311,33.240267,레져/스포츠,화순금모래해변,제주특별자치도 서귀포시 안덕면 화순리 776-8,화순금모래해수욕장,
2,23,126.394655,33.277406,레져/스포츠,대유수렵장,제주특별자치도 서귀포시 상예동 144,.,
3,25,126.393129,33.314993,레져/스포츠,핀크스골프클럽(퍼블릭),제주특별자치도 서귀포시 안덕면 상천리 산 62-3,"핀크스GC(퍼블릭),핀크스골프장(퍼블릭),SK핀크스골프클럽(퍼블릭)",
5,33,126.406742,33.250792,레져/스포츠,중문CC,제주특별자치도 서귀포시 색달동 2864-36,"중문컨트리클럽,중문골프장",
6,34,126.414491,33.244726,레져/스포츠,중문색달해변,제주특별자치도 서귀포시 색달동 2812-2,중문해수욕장,
...,...,...,...,...,...,...,...,...
799,5674,126.619856,33.456048,레져/스포츠,한라경찰수련원,제주특별자치도 제주시 명림로 381,.,
800,5675,126.702840,33.273728,레져/스포츠,아쿠아나,제주특별자치도 서귀포시 남원읍 남원리 2384-1,.,
801,5942,126.543762,33.472361,레져/스포츠,제이앤제이골프,제주특별자치도 제주시 아라일동 6084-6,.,
802,5964,126.234416,33.389291,레져/스포츠,금능해수욕장야영장,제주특별자치도 제주시 한림읍 금능리 2030,.,
804,5980,126.333311,33.240400,레져/스포츠,화순해변야영장,제주특별자치도 서귀포시 안덕면 화순리 776-8,.,

### 5. 문화/예술

In [121]:
culture = pd.read_excel("POI_문화_종교_예술.xlsx")
culture.head()

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name
0,8,126.289463,33.305817,문화/종교/예술,오설록티뮤지엄,제주특별자치도 서귀포시 안덕면 서광리 1235-3,"설록차뮤지엄오설록,오설록녹차박물관"
1,11,126.842390,33.324083,문화/종교/예술,제주민속촌박물관,제주특별자치도 서귀포시 표선면 표선리 40-1,.
2,40,126.262038,33.412789,문화/종교/예술,한수풀문화센터,제주특별자치도 제주시 한림읍 한림리 138,.
3,110,126.432523,33.442713,문화/종교/예술,제주공룡랜드,제주특별자치도 제주시 애월읍 광령리 2677-1,공룡랜드
4,125,126.474293,33.481684,문화/종교/예술,이조당,제주특별자치도 제주시 노형동 1430-7,.

In [122]:
culture["검색결과"] = ""
culture.head()

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,8,126.289463,33.305817,문화/종교/예술,오설록티뮤지엄,제주특별자치도 서귀포시 안덕면 서광리 1235-3,"설록차뮤지엄오설록,오설록녹차박물관",
1,11,126.842390,33.324083,문화/종교/예술,제주민속촌박물관,제주특별자치도 서귀포시 표선면 표선리 40-1,.,
2,40,126.262038,33.412789,문화/종교/예술,한수풀문화센터,제주특별자치도 제주시 한림읍 한림리 138,.,
3,110,126.432523,33.442713,문화/종교/예술,제주공룡랜드,제주특별자치도 제주시 애월읍 광령리 2677-1,공룡랜드,
4,125,126.474293,33.481684,문화/종교/예술,이조당,제주특별자치도 제주시 노형동 1430-7,.,

In [123]:
import time 
for idx,i in culture.iterrows():
    time.sleep(1.5)
    if len(i["장소명"]) > 2: 
        if i["장소명"][:2] == "제주":
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote(i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                culture.loc[idx, "검색결과"] = "없는 장소"
        else:
            url_base="https://openapi.naver.com/v1/search/local.json?query="
            keyword = quote("제주" + i["장소명"])
            url_middle="&display=5 & start=1"
            url = url_base + keyword + url_middle
            result = requests.get(url,headers = headers).json()
            if result["total"] == 0:
                culture.loc[idx, "검색결과"] = "없는 장소"
    else:
        url_base="https://openapi.naver.com/v1/search/local.json?query="
        keyword = quote("제주" + i["장소명"])
        url_middle="&display=5 & start=1"
        url = url_base + keyword + url_middle
        result = requests.get(url,headers = headers).json()
        if result["total"] == 0:
                culture.loc[idx, "검색결과"] = "없는 장소"

In [124]:
len(culture[culture["검색결과"] =="없는 장소"])

74

In [129]:
culture = culture.drop(culture[culture["검색결과"]=="없는 장소"].index)
culture

,Unnamed: 0,위치좌표 X축값,위치좌표 Y축값,구분,장소명,소재지,Additional_Name,검색결과
0,8,126.289463,33.305817,문화/종교/예술,오설록티뮤지엄,제주특별자치도 서귀포시 안덕면 서광리 1235-3,"설록차뮤지엄오설록,오설록녹차박물관",
1,11,126.842390,33.324083,문화/종교/예술,제주민속촌박물관,제주특별자치도 서귀포시 표선면 표선리 40-1,.,
2,40,126.262038,33.412789,문화/종교/예술,한수풀문화센터,제주특별자치도 제주시 한림읍 한림리 138,.,
3,110,126.432523,33.442713,문화/종교/예술,제주공룡랜드,제주특별자치도 제주시 애월읍 광령리 2677-1,공룡랜드,
4,125,126.474293,33.481684,문화/종교/예술,이조당,제주특별자치도 제주시 노형동 1430-7,.,
...,...,...,...,...,...,...,...,...
228,5082,126.669837,33.536590,문화/종교/예술,일관도명세법당,제주특별자치도 제주시 조천읍 함덕리 908,.,
229,5188,126.551167,33.244812,문화/종교/예술,기당미술관,제주특별자치도 서귀포시 서홍동 34,서귀포기당미술관,
230,5278,126.823649,33.536725,문화/종교/예술,제주지부북군지회한동분회,제주특별자치도 제주시 구좌읍 한동리 1787-1,.,
231,6032,126.528500,33.513540,문화/종교/예술,동문모텔아라리오뮤지엄,제주특별자치도 제주시 일도일동 1159,.,
233,6431,126.522551,33.511523,문화/종교/예술,씨너스제주(구),제주특별자치도 제주시 중앙로14길 18,.,

In [130]:
jeju_accom.to_excel("숙박_장소처리.xlsx")

In [131]:
jeju_tour.to_excel("관광지_장소처리.xlsx")

In [134]:
park.to_excel("공원_장소처리.xlsx")

In [135]:
leisure.to_excel("레저_스포츠_장소처리.xlsx")

In [136]:
culture.to_excel("문화예술_장소처리.xlsx")

## 3. 이미지 크롤링

In [44]:
url_base="https://openapi.naver.com/v1/search/image?query="
keyword = quote("서귀포호텔	")
url_middle="&display=5&start=1&sort=sim"

url = url_base + keyword + url_middle

result = requests.get(url,headers = headers).json()
result

{'lastBuildDate': 'Mon, 10 Jan 2022 12:32:53 +0900',
 'total': 24714,
 'start': 1,
 'display': 5,
 'items': [{'title': '라마다 앙코르 제주 서귀포 특가 호텔예약, (서귀포, 한국) 호텔추천 | 호텔스닷컴 서귀포에 있는 라마다 앙코르 제주 서귀포 (Ramada Encore Jeju Seogwipo)',
   'link': 'https://thumbnails.trvl-media.com/CI6McqfFFWGf8dPqmEjp325kKgg=/773x530/smart/filters:quality(60)/images.trvl-media.com/hotels/11000000/10350000/10344600/10344521/223355ad_z.jpg',
   'thumbnail': 'https://search.pstatic.net/sunny/?src=https://thumbnails.trvl-media.com/CI6McqfFFWGf8dPqmEjp325kKgg=/773x530/smart/filters:quality(60)/images.trvl-media.com/hotels/11000000/10350000/10344600/10344521/223355ad_z.jpg&type=b150',
   'sizeheight': '530',
   'sizewidth': '773'},
  {'title': '서귀포 가볼만한곳, 제주서귀포호텔 오션팰리스 호텔',
   'link': 'http://post.phinf.naver.net/MjAxNzA2MTlfMjQ2/MDAxNDk3ODAyOTE5MTMz.HcyLpyZfq1BcdGQGHEoTmKH2r6vJmsERxjZJolySamgg.UTkeqnfmWXu2zgOKiqFerqA5A-doFZKe7lkp0yDQOPYg.JPEG/IeUGd-r8OekUACXSLisvR_s4oYXw.jpg',
   'thumbnail': 'https://search.pstatic.net/common/?src=http://post.phinf.naver.net/MjAxNzA2MTlfMjQ2/MDAxNDk3ODAyOTE5MTMz.HcyLpyZfq1BcdGQGHEoTmKH2r6vJmsERxjZJolySamgg.UTkeqnfmWXu2zgOKiqFerqA5A-doFZKe7lkp0yDQOPYg.JPEG/IeUGd-r8OekUACXSLisvR_s4oYXw.jpg&type=b150',
   'sizeheight': '734',
   'sizewidth': '1164'},
  {'title': "'미니멀리즘 스타일' 호텔의 매력?...서귀포에 '라마다 앙코르' 오픈",
   'link': 'http://imgnews.naver.net/image/213/2015/04/14/20150414_1428986831_43293800_1_99_20150414135104.jpg',
   'thumbnail': 'https://search.pstatic.net/common/?src=http://imgnews.naver.net/image/213/2015/04/14/20150414_1428986831_43293800_1_99_20150414135104.jpg&type=b150',
   'sizeheight': '571',
   'sizewidth': '520'},
  {'title': '서귀포 저렴한 호텔 추천 <디아일랜드블루>',
   'link': 'http://post.phinf.naver.net/MjAxODA4MDNfMjAx/MDAxNTMzMjg4ODMwOTE2.LMBfjVq_XOrAsswlxlVt5OlpjUWpQKzAFMjDOwFufKwg.6E9DzLH69svs3k1syPLgBYNfqjfLR2AVODYlEELCnosg.JPEG/I4eVxxp_UFJ-vqJUZPqR7c1uromc.jpg',
   'thumbnail': 'https://search.pstatic.net/common/?src=http://post.phinf.naver.net/MjAxODA4MDNfMjAx/MDAxNTMzMjg4ODMwOTE2.LMBfjVq_XOrAsswlxlVt5OlpjUWpQKzAFMjDOwFufKwg.6E9DzLH69svs3k1syPLgBYNfqjfLR2AVODYlEELCnosg.JPEG/I4eVxxp_UFJ-vqJUZPqR7c1uromc.jpg&type=b150',
   'sizeheight': '3000',
   'sizewidth': '2250'},
  {'title': '제주 라마다 앙코르서귀포 호텔투숙기간 7월까지 확보 - 티몬 [티몬] 제주 라마다 앙코르서귀포 호텔투숙기간 7월까지 확보',
   'link': 'http://img1.tmon.kr/cdn3/deals/2020/05/06/3475714922/original_3475714922_front_f6de8_1588754720production.jpg',
   'thumbnail': 'https://search.pstatic.net/sunny/?src=http://img1.tmon.kr/cdn3/deals/2020/05/06/3475714922/original_3475714922_front_f6de8_1588754720production.jpg&type=b150',
   'sizeheight': '700',
   'sizewidth': '700'}]}